SLACK_WEBHOOK=https://hooks.slack.com/services/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
OPENAI_API_KEY=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
OPENAI_BASE_URL=https://api.openai.com/v1
GEMINI_API_KEY=AIzaSyCXdOm57Pce_GEqgdtLLeE_mvxAFRzCkho